version: "3"

services:
  graphql:
    container_name: learn-graphql
    build: ./graphql
    tty: true
    working_dir: /app
    ports:
      - 4000:4000
    volumes:
      - ./graphql:/app:cached
      - graphql-node_modules:/app/node_modules
  app:
    container_name: learn-graphql-fe
    build: ./frontend
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - graphql
    volumes:
      - ./frontend:/app:cached
      - frontend-node_modules:/app/node_modules

volumes:
  graphql-node_modules: {}
  frontend-node_modules: {}
