version: "3"

services:
  app:
    container_name: learn-graphql
    build: .
    tty: true
    # environment:
    # - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    ports:
      - 4000:4000
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules

volumes:
  node_modules: {}
